const items=[
["Fiber Optik Kablolama ve Montaj","Yüksek bant genişliği ve uzun mesafeli iletişim gerektiren projelerde fiber optik altyapı kurulumu, kablo çekimi, fusion sonlandırma, patch panel düzeni ve devreye alma hizmetleri."],
["Yapısal Kablolama (Data + Tel)","Projelendirilmiş altyapılarda bakır ve fiber kablo çekimi, sonlandırma, merkez sistem odasının oluşturulması veya mevcut sistem odasının toparlanması ve aktif cihazların konumlandırılması."],
["Aktif Network Switch ve Kurulum","Ağ topolojisi ve kapasite ihtiyacına uygun yönetilebilir switch çözümleri; VLAN destekli ve büyümeye uygun network altyapılarının kurulumu."],
["Merkez ve Kenar Rack Kabin","Sistem ekipmanlarının güvenli ve düzenli konumlandırılması için rack kabinet ve aksesuar çözümleri; proje ihtiyacına uygun havalandırma ve koruma seçenekleri."],
["Kablosuz İnternet / Wi‑Fi","Indoor ve outdoor erişim noktalarıyla kablolu ağların kapsama ihtiyacına uygun kablosuz ağlara dönüştürülmesi, montaj ve kurulum hizmetleri."],
["IP Kamera Sistemleri","IP kamera satış ve kurulumu; lokal ağ veya internet üzerinden yetkili erişim, kayıt, hareket algılama ve ağ altyapısıyla entegre güvenlik çözümleri."],
["UPS Güç Kaynakları","Kritik sistemleri şebeke problemleri ve enerji kesintilerine karşı koruyan kesintisiz güç kaynağı çözümlerinin seçimi, satışı ve kurulumu."],
["UPS + Şebeke Elektrik","UPS ve şebeke enerji dağıtımı için elektrik kablolaması, kat ve ana pano montajı, enerji prizleri ve topraklama çalışmaları."],
["Sistem Odası Düzenleme ve Kurulum","Sunucu, depolama, yedekleme ve network katmanlarının bulunduğu sistem odalarının performanslı, yönetilebilir ve büyümeye uygun biçimde planlanması ve düzenlenmesi."]
];
export default function Services(){return <main><header className="nav"><a className="brand brandImage" href="/"><img className="brandLogo" src="/runtechh-logo.png" alt="Runtechh Bilişim Teknolojileri" /></a><nav><a href="/#kurumsal">Biz Kimiz</a><a href="/hizmetler">Hizmetlerimiz</a><a href="/referanslar">Referanslar</a><a href="/iletisim">İletişim</a></nav><a className="smallCta" href="tel:+905326222235">Ücretsiz Keşif</a></header><section className="subHero"><span className="eyebrow">RUNTECHH ÇÖZÜMLERİ</span><h1>Kurumsal bilişim<br/><em>altyapı hizmetleri.</em></h1><p>Fiber optikten sistem odasına kadar Runtechh hizmet kapsamını proje odaklı ve anlaşılır bir yapıda sunuyoruz.</p></section><section className="serviceList">{items.map((x,i)=><article key={x[0]}><span>{String(i+1).padStart(2,"0")}</span><div><h2>{x[0]}</h2><p>{x[1]}</p><a href="/iletisim">Projeniz için bilgi alın →</a></div></article>)}</section><section className="contact compact"><span className="eyebrow">ÜCRETSİZ KEŞİF</span><h2>İhtiyacınızı birlikte planlayalım.</h2><p>Antalya ve çevresindeki projeleriniz için bize ulaşın.</p><a className="primary" href="tel:+905326222235">0 532 622 22 35</a></section><footer><a className="brand brandImage" href="/"><img className="brandLogo" src="/runtechh-logo.png" alt="Runtechh Bilişim Teknolojileri" /></a><span>© 2026 Runtechh Bilişim Teknolojileri</span></footer></main>}