import MobileMenu from "../components/MobileMenu";
const items=[
["Fiber Optik Kablolama ve Montaj","Yüksek bant genişliği ve uzun mesafeli iletişim gerektiren projelerde fiber optik altyapı kurulumu, fusion sonlandırma, patch panel düzeni ve devreye alma.","https://assets.webfervor.com/image/63/ce8cb180159d2d3b4a289d8e93aceba3.jpeg","Fiber optik sonlandırma ve altyapı çalışması"],
["Yapısal Kablolama (Data + Tel)","Bakır ve fiber kablo çekimi, sonlandırma, patch panel düzeni ve merkez sistem odasının profesyonel biçimde oluşturulması.","https://securevisionsolutions.com/assets/structured-network-cabling-installation.png","Yapısal kablolama ve patch panel"],
["Aktif Network Switch ve Kurulum","Ağ topolojisi ve kapasite ihtiyacına uygun yönetilebilir switch çözümleri; VLAN destekli ve büyümeye uygun network altyapıları.","https://www.lvt.com.tr/storage/app/uploads/public/5f4/111/42d/thumb_456_0_480_0_0_crop.jpg","Network switch ve rack kabinet"],
["Merkez ve Kenar Rack Kabin","Sistem ekipmanlarının güvenli ve düzenli konumlandırılması için rack kabinet, aksesuar, havalandırma ve kablo yönetimi çözümleri.","https://rackmountsolutions.net/cdn/shop/collections/data-center-server-racks.png?v=1764869883","Rack kabinet ve sistem odası"],
["Kablosuz İnternet / Wi‑Fi","Indoor ve outdoor erişim noktalarıyla kapsama ihtiyacına uygun, stabil ve yönetilebilir kurumsal kablosuz ağ çözümleri.","https://images.unsplash.com/photo-1606768666853-403c90a981ad?auto=format&fit=crop&w=1400&q=82","Kurumsal Wi-Fi erişim noktası"],
["IP Kamera Sistemleri","IP kamera, kayıt ve ağ altyapısını birlikte ele alan; lokal veya uzaktan yetkili erişime uygun güvenlik çözümleri.","https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=1400&q=82","IP güvenlik kamera sistemi"],
["UPS Güç Kaynakları","Kritik sistemleri enerji kesintileri ve şebeke problemlerine karşı koruyan UPS çözümlerinin seçimi, kurulumu ve devreye alınması.","https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1400&q=82","Kritik sistem altyapısı ve güç sürekliliği"],
["UPS + Şebeke Elektrik","UPS ve şebeke enerji dağıtımı için elektrik kablolaması, pano montajı, enerji prizleri ve topraklama çalışmaları.","https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=1400&q=82","Elektrik altyapısı ve pano çalışması"],
["Sistem Odası Düzenleme ve Kurulum","Sunucu, depolama, yedekleme ve network katmanlarının performanslı, yönetilebilir ve büyümeye uygun biçimde planlanması.","https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1400&q=82","Profesyonel sistem odası"]
];
export default function Services(){return <main><header className="nav"><a className="brand brandImage" href="/"><img className="brandLogo" src="https://raw.githubusercontent.com/Teknoant/runtechh/main/runtechh-logo.png" alt="Runtechh Bilişim Teknolojileri" /></a><nav><a href="/biz-kimiz">Biz Kimiz</a><a href="/hizmetler">Hizmetlerimiz</a><a href="/referanslar">Çalıştığımız Markalar</a><a href="/iletisim">İletişim</a></nav><a className="smallCta whatsappCta" href="https://wa.me/905326222235?text=Merhaba%20Runtechh%2C%20%C3%BCcretsiz%20ke%C5%9Fif%20hakk%C4%B1nda%20bilgi%20almak%20istiyorum." target="_blank" rel="noopener noreferrer">WhatsApp</a><MobileMenu/></header><section className="servicesHero"><div><span className="eyebrow">RUNTECHH ÇÖZÜMLERİ</span><h1>Altyapının her katmanında<br/><em>tek çözüm ortağı.</em></h1><p>Fiber, network, Wi‑Fi, güvenlik ve sistem odası altyapılarını keşiften devreye almaya kadar bütün olarak planlıyoruz.</p><a className="primary" href="/iletisim">Projenizi Konuşalım →</a></div><img src="https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1800&q=85" alt="Kurumsal veri merkezi ve network altyapısı"/></section><section className="servicesIntro"><span className="eyebrow">HİZMETLERİMİZ</span><h2>İhtiyaçtan değil,<br/>altyapının bütününden başlıyoruz.</h2></section><section className="serviceVisualList">{items.map((x,i)=><article key={x[0]}><div className="servicePhoto"><img src={x[2]} alt={x[3]}/><span>{String(i+1).padStart(2,"0")}</span></div><div className="serviceText"><small>RUNTECHH / {String(i+1).padStart(2,"0")}</small><h2>{x[0]}</h2><p>{x[1]}</p><a href="/iletisim">Bu hizmet için keşif talep edin →</a></div></article>)}</section><section className="serviceBottomCta"><span className="eyebrow">ANTALYA VE ÇEVRESİ</span><h2>Projenizi sahada birlikte değerlendirelim.</h2><p>Doğru altyapı için ilk adım doğru keşiftir.</p><a className="primary" href="tel:+905326222235">0 532 622 22 35</a></section><footer><a className="brand brandImage" href="/"><img className="brandLogo" src="https://raw.githubusercontent.com/Teknoant/runtechh/main/runtechh-logo.png" alt="Runtechh Bilişim Teknolojileri" /></a><span>© 2026 Runtechh Bilişim Teknolojileri</span></footer></main>}