const services=[
{title:"Fiber Optik",text:"Yüksek hızlı ve kararlı veri iletişimi için fiber optik altyapı, sonlandırma, test ve devreye alma çözümleri."},
{title:"Yapısal Kablolama",text:"Ofis, otel, fabrika ve ticari yapılarda düzenli, ölçeklenebilir data ve telefon kablolama altyapıları."},
{title:"Aktif Network & Switch",text:"İşletmenizin kapasitesine uygun switch, router ve aktif ağ ekipmanlarının projelendirilmesi ve kurulumu."},
{title:"Rack Kabinet",text:"Network ekipmanlarının güvenli, düzenli ve servis edilebilir biçimde konumlandırılması için kabinet çözümleri."},
{title:"Wi‑Fi Çözümleri",text:"Kapsama, kapasite ve kullanıcı yoğunluğuna göre profesyonel kablosuz ağ planlama ve uygulaması."},
{title:"IP Kamera",text:"İşletmeler için IP kamera, kayıt ve uzaktan izleme altyapılarının kurulumu ve devreye alınması."},
{title:"UPS & Elektrik",text:"Kritik bilişim sistemlerinin sürekliliğini destekleyen UPS ve ilgili enerji altyapısı çözümleri."},
{title:"Sistem Odası",text:"Kabinet, enerji, network ve kablolama bileşenlerinin birlikte planlandığı düzenli sistem odası uygulamaları."}
];
export default function Home(){return <main>
<header className="nav"><a className="brand" href="#">RUNTECHH<span>BİLİŞİM TEKNOLOJİLERİ</span></a><nav><a href="#kurumsal">Biz Kimiz</a><a href="#hizmetler">Hizmetlerimiz</a><a href="/referanslar">Referanslar</a><a href="#iletisim">İletişim</a></nav><a className="smallCta" href="tel:+905326222235">Ücretsiz Keşif</a></header>
<section className="hero"><div><span className="eyebrow">ANTALYA • PROFESYONEL BİLİŞİM ALTYAPISI</span><h1>Altyapınız<br/><em>işinizi yavaşlatmasın.</em></h1><p>Fiber optik, yapısal kablolama, network, Wi‑Fi, IP kamera ve sistem odası çözümlerini tek noktadan planlıyor ve uyguluyoruz.</p><div className="actions"><a className="primary" href="tel:+905326222235">Keşif Talep Et</a><a className="secondary" href="/hizmetler">Çözümlerimizi İncele →</a></div><div className="trust"><span>FİBER OPTİK</span><span>NETWORK</span><span>IP KAMERA</span><span>SİSTEM ODASI</span></div></div><div className="visual"><div className="grid"></div><div className="orb"></div><div className="pulse p1"></div><div className="pulse p2"></div><div className="stat"><small>RUNTECHH</small><b>Kurumsal Altyapı</b><span>Keşif • Projelendirme • Kurulum</span></div></div></section>
<section id="kurumsal" className="about"><div><span className="eyebrow">BİZ KİMİZ?</span><h2>İşletmenizin teknoloji altyapısını doğru temeller üzerine kuruyoruz.</h2></div><div><p>Runtechh Bilişim Teknolojileri; kurumsal yapılara ağ, haberleşme, güvenlik ve sistem altyapısı çözümleri sunar. Projeyi keşif aşamasından başlayarak değerlendirir, ihtiyaca uygun altyapıyı planlar ve uygulamasını gerçekleştirir.</p><p className="muted">Hedefimiz yalnızca sistemi çalıştırmak değil; düzenli, yönetilebilir ve gelecekte büyütülebilir bir altyapı oluşturmaktır.</p></div></section>
<section id="hizmetler" className="services"><div className="sectionHead"><div><span className="eyebrow">HİZMETLERİMİZ</span><h2>Tek altyapı.<br/>Sekiz uzmanlık alanı.</h2></div><p>Fiziksel kablolamadan aktif ağ cihazlarına kadar bütün bileşenleri birbiriyle uyumlu şekilde ele alıyoruz.</p></div><div className="cards">{services.map((s,i)=><article key={s.title}><span className="num">{String(i+1).padStart(2,"0")}</span><div className="icon">⌁</div><h3>{s.title}</h3><p>{s.text}</p><a href="/hizmetler">Detayları Gör →</a></article>)}</div></section>
<section id="referanslar" className="references"><span className="eyebrow">PROJE YAKLAŞIMIMIZ</span><h2>Keşiften devreye almaya<br/>tek ekip, tek sorumluluk.</h2><div className="steps"><div><b>01</b><h3>Keşif</h3><p>Mevcut yapı ve ihtiyaçları yerinde değerlendiriyoruz.</p></div><div><b>02</b><h3>Projelendirme</h3><p>Doğru topoloji, ekipman ve uygulama planını oluşturuyoruz.</p></div><div><b>03</b><h3>Uygulama</h3><p>Kablolama ve sistem kurulumunu profesyonel biçimde gerçekleştiriyoruz.</p></div><div><b>04</b><h3>Devreye Alma</h3><p>Test, kontrol ve son düzenlemelerle sistemi teslim ediyoruz.</p></div></div><a className="sectionLink" href="/referanslar">Referanslar ve proje yaklaşımı →</a></section>
<section id="iletisim" className="contact"><span className="eyebrow">İLETİŞİM</span><h2>Projenizi konuşalım.</h2><p>Antalya ve çevresindeki bilişim altyapısı projeleriniz için Runtechh ile iletişime geçin.</p><div className="contactGrid"><a href="tel:+905326222235"><small>TELEFON</small><b>0 532 622 22 35</b></a><a href="mailto:bilisim@runtechh.com.tr"><small>E-POSTA</small><b>bilisim@runtechh.com.tr</b></a><div><small>ADRES</small><b>Varlık Mah. 100. Yıl Bulvarı No:34 K:1 D:2<br/>Muratpaşa / Antalya</b></div></div></section>
<footer><a className="brand" href="#">RUNTECHH<span>BİLİŞİM TEKNOLOJİLERİ</span></a><span>© 2026 Runtechh Bilişim Teknolojileri</span><a href="tel:+905326222235">0 532 622 22 35</a></footer>
</main>}