const services=[
{title:"Fiber Optik",text:"Yüksek hızlı ve kararlı veri iletişimi için fiber optik altyapı, sonlandırma, test ve devreye alma çözümleri."},
{title:"Yapısal Kablolama",text:"Ofis, otel, fabrika ve ticari yapılarda düzenli, ölçeklenebilir data ve telefon kablolama altyapıları."},
{title:"Aktif Network & Switch",text:"İşletmenizin kapasitesine uygun switch, router ve aktif ağ ekipmanlarının projelendirilmesi ve kurulumu."},
{title:"Rack Kabinet",text:"Network ekipmanlarının güvenli, düzenli ve servis edilebilir biçimde konumlandırılması için kabinet çözümleri."},
{title:"Wi‑Fi Çözümleri",text:"Kapsama, kapasite ve kullanıcı yoğunluğuna göre profesyonel kablosuz ağ planlama ve uygulaması."},
{title:"IP Kamera",text:"İşletmeler için IP kamera, kayıt ve uzaktan izleme altyapılarının kurulumu ve devreye alınması."},
{title:"UPS & Elektrik",text:"Kritik bilişim sistemlerinin sürekliliğini destekleyen UPS ve ilgili enerji altyapısı çözümleri."},
{title:"Sistem Odası",text:"Kabinet, enerji, network ve kablolama bileşenlerinin birlikte planlandığı düzenli sistem odası uygulamaları."}
];
export default function Home(){return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"LocalBusiness","name":"Runtechh Bilişim Teknolojileri","url":"https://www.runtechh.com.tr","telephone":"+905326222235","email":"runtechh@runtechh.com.tr","address":{"@type":"PostalAddress","streetAddress":"Varlık Mahallesi 100. Yıl Bulvarı No:34 K:1 D:2","addressLocality":"Muratpaşa","addressRegion":"Antalya","addressCountry":"TR"},"areaServed":"Antalya","description":"Fiber optik, yapısal kablolama, network, Wi-Fi, IP kamera, UPS ve sistem odası çözümleri."})}}/>
<header className="nav"><a className="brand brandImage" href="#"><img className="brandLogo" src="https://raw.githubusercontent.com/Teknoant/runtechh/main/runtechh-logo.png" alt="Runtechh Bilişim Teknolojileri" /></a><nav><a href="/biz-kimiz">Biz Kimiz</a><a href="#hizmetler">Hizmetlerimiz</a><a href="/referanslar">Referanslar</a><a href="/iletisim">İletişim</a></nav><a className="smallCta" href="tel:+905326222235">Ücretsiz Keşif</a></header>
<section className="hero"><div><span className="eyebrow">ANTALYA • PROFESYONEL BİLİŞİM ALTYAPISI</span><h1>Altyapınız<br/><em>işinizi yavaşlatmasın.</em></h1><p>Fiber optik, yapısal kablolama, network, Wi‑Fi, IP kamera ve sistem odası çözümlerini tek noktadan planlıyor ve uyguluyoruz.</p><div className="actions"><a className="primary" href="tel:+905326222235">Keşif Talep Et</a><a className="secondary" href="/hizmetler">Çözümlerimizi İncele →</a></div><div className="trust"><span>FİBER OPTİK</span><span>NETWORK</span><span>IP KAMERA</span><span>SİSTEM ODASI</span></div></div><div className="visual photoHero"><img src="https://asia.scalefibre.com/images/infographics/dc-patching.webp" alt="Fiber optik ve network kabinet altyapısı" /><div className="photoShade"></div><div className="stat"><small>RUNTECHH</small><b>Kurumsal Altyapı</b><span>Keşif • Projelendirme • Kurulum</span></div></div></section>
<section id="kurumsal" className="about"><div><span className="eyebrow">BİZ KİMİZ?</span><h2>İşletmenizin teknoloji altyapısını doğru temeller üzerine kuruyoruz.</h2></div><div><p>Runtechh Bilişim Teknolojileri; kurumsal yapılara ağ, haberleşme, güvenlik ve sistem altyapısı çözümleri sunar. Projeyi keşif aşamasından başlayarak değerlendirir, ihtiyaca uygun altyapıyı planlar ve uygulamasını gerçekleştirir.</p><p className="muted">Hedefimiz yalnızca sistemi çalıştırmak değil; düzenli, yönetilebilir ve gelecekte büyütülebilir bir altyapı oluşturmaktır.</p></div></section>
<section className="visualBand"><div className="visualIntro"><span className="eyebrow">SAHADAKİ TEKNOLOJİ</span><h2>Doğru altyapı, düzenli uygulama.</h2></div><div className="visualTiles"><figure><img src="https://images.squarespace-cdn.com/content/v1/56ca8729f850827f40a70641/1485461763281-WVQFMBN90V7A8PCHEUHL/it-rack-cabling-management-solution-provider" alt="Yapısal kablolama ve patch panel" /><figcaption>Yapısal Kablolama</figcaption></figure><figure><img src="https://upload.jaknot.com/2026/05/images/products/61faec/original/cisco-wireless-access-point-ap-80211ac-wave-2-air-ap3802i-h-k9.png" alt="Kurumsal Wi-Fi erişim noktası" /><figcaption>Kurumsal Wi-Fi</figcaption></figure><figure><img src="https://alpha9solutions.com/cdn/shop/articles/yvxc0jfnkeexyhoqnmkp.png?v=1776438099" alt="Ticari bina IP kamera sistemi" /><figcaption>IP Kamera Sistemleri</figcaption></figure></div></section><section id="hizmetler" className="services"><div className="sectionHead"><div><span className="eyebrow">HİZMETLERİMİZ</span><h2>Tek altyapı.<br/>Sekiz uzmanlık alanı.</h2></div><p>Fiziksel kablolamadan aktif ağ cihazlarına kadar bütün bileşenleri birbiriyle uyumlu şekilde ele alıyoruz.</p></div><div className="cards">{services.map((s,i)=><article key={s.title}><span className="num">{String(i+1).padStart(2,"0")}</span><div className="icon" dangerouslySetInnerHTML={{__html:["<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M5 19c2-6 5-10 13-13\"/><path d=\"M7 20l-3-3 3-3 3 3z\"/><circle cx=\"18\" cy=\"6\" r=\"2\"/><path d=\"M10 15c2-4 5-6 8-7\"/></svg>","<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M4 7h4v4H4zM16 7h4v4h-4zM10 15h4v4h-4z\"/><path d=\"M8 9h8M6 11v3h6v1M18 11v3h-6\"/></svg>","<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><rect x=\"3\" y=\"7\" width=\"18\" height=\"10\" rx=\"2\"/><path d=\"M7 12h.01M11 12h.01M15 12h2M5 4h14\"/></svg>","<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><rect x=\"6\" y=\"3\" width=\"12\" height=\"18\" rx=\"1\"/><path d=\"M9 7h6M9 11h6M9 15h6\"/><circle cx=\"9\" cy=\"18\" r=\".7\"/></svg>","<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M4 9a12 12 0 0 1 16 0M7 12a8 8 0 0 1 10 0M10 15a4 4 0 0 1 4 0\"/><circle cx=\"12\" cy=\"18\" r=\"1\"/></svg>","<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M4 9h11l4 3-4 3H4z\"/><circle cx=\"10\" cy=\"12\" r=\"2.5\"/><path d=\"M19 12h3M7 17v3\"/></svg>","<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><rect x=\"5\" y=\"4\" width=\"14\" height=\"16\" rx=\"2\"/><path d=\"M9 8h6M12 11v3M10 14h4M8 17h8\"/><path d=\"M12 2v2\"/></svg>","<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><rect x=\"5\" y=\"3\" width=\"14\" height=\"18\" rx=\"1\"/><path d=\"M8 7h8M8 11h8M8 15h8\"/><circle cx=\"9\" cy=\"18\" r=\".7\"/><circle cx=\"12\" cy=\"18\" r=\".7\"/></svg>"][i]}}/><h3>{s.title}</h3><p>{s.text}</p><a href="/hizmetler">Detayları Gör →</a></article>)}</div></section>
<section className="fieldWork"><div className="fieldHead"><div><span className="eyebrow">UZMANLIK SAHADA BELLİ OLUR</span><h2>Fiberden sistem odasına,<br/>altyapının her katmanı.</h2></div><p>Kurumsal altyapının kritik noktalarını; temiz kablolama, doğru sonlandırma ve yönetilebilir kabinet düzeniyle ele alıyoruz.</p></div><div className="fieldGallery"><figure className="fieldMain"><img src="https://assets.webfervor.com/image/63/ce8cb180159d2d3b4a289d8e93aceba3.jpeg" alt="Fiber optik füzyon ve sonlandırma çalışması" /><figcaption><b>Fiber Optik</b><span>Sonlandırma • Test • Devreye Alma</span></figcaption></figure><figure><img src="https://securevisionsolutions.com/assets/structured-network-cabling-installation.png" alt="Profesyonel yapısal kablolama ve patch panel düzeni" /><figcaption><b>Yapısal Kablolama</b><span>Patch Panel • Data • Etiketleme</span></figcaption></figure><figure><img src="https://www.lvt.com.tr/storage/app/uploads/public/5f4/111/42d/thumb_456_0_480_0_0_crop.jpg" alt="Network switch ve rack kabinet kablolaması" /><figcaption><b>Network & Rack</b><span>Switch • Kabinet • Kablo Yönetimi</span></figcaption></figure></div></section>
<section className="why"><div className="whyLead"><span className="eyebrow">NEDEN RUNTECHH?</span><h2>Altyapıyı yalnız kurmuyoruz.<br/>Yönetilebilir hale getiriyoruz.</h2><p>Kurumsal bilişim altyapısında performans kadar düzen, servis kolaylığı ve büyüyebilirlik de önemlidir. Fiziksel kablolamadan aktif cihazlara kadar sistemi bir bütün olarak ele alıyoruz.</p></div><div className="whyGrid"><article><b>01</b><h3>Tek noktadan çözüm</h3><p>Fiber, data, network, Wi-Fi, kamera, enerji ve sistem odası aynı proje yaklaşımıyla yönetilir.</p></article><article><b>02</b><h3>Sahaya özel planlama</h3><p>Yapının kullanım yoğunluğu, mesafeleri ve kapasitesi dikkate alınır.</p></article><article><b>03</b><h3>Düzenli teslim</h3><p>Kabinet, patch panel ve bağlantılar servis edilebilir biçimde düzenlenir.</p></article></div></section>
<section id="referanslar" className="projectShowcase"><div className="projectVisual"><img src="https://rackmountsolutions.net/cdn/shop/collections/data-center-server-racks.png?v=1764869883" alt="Profesyonel sistem odası ve rack kabinet altyapısı" /></div><div className="projectCopy"><span className="eyebrow">PROJE YAKLAŞIMI</span><h2>Keşiften devreye almaya tek ekip, tek sorumluluk.</h2><p>Mevcut yapıyı inceliyor, ihtiyacı projelendiriyor, uyguluyor ve sistemi test ederek devreye alıyoruz.</p><div className="projectProcess"><div><b>01</b><span>Keşif</span></div><div><b>02</b><span>Projelendirme</span></div><div><b>03</b><span>Uygulama</span></div><div><b>04</b><span>Devreye Alma</span></div></div><a className="primary" href="/referanslar">Proje yaklaşımımızı inceleyin</a></div></section>
<section className="finalCta"><div><span className="eyebrow">ANTALYA • KURUMSAL BİLİŞİM ALTYAPISI</span><h2>Yeni projeniz için<br/>doğru altyapıyla başlayın.</h2></div><div><p>Fiber optik, network, Wi-Fi, IP kamera ve sistem odası projeleriniz için keşif talep edin.</p><div className="ctaActions"><a className="primary" href="tel:+905326222235">0 532 622 22 35</a><a className="outlineCta" href="/iletisim">İletişime Geç →</a></div></div></section>
<section id="iletisim" className="contact"><span className="eyebrow">İLETİŞİM</span><h2>Projenizi konuşalım.</h2><p>Antalya ve çevresindeki bilişim altyapısı projeleriniz için Runtechh ile iletişime geçin.</p><div className="contactGrid"><a href="tel:+905326222235"><small>TELEFON</small><b>0 532 622 22 35</b></a><a href="mailto:runtechh@runtechh.com.tr"><small>E-POSTA</small><b>runtechh@runtechh.com.tr</b></a><div><small>ADRES</small><b>Varlık Mah. 100. Yıl Bulvarı No:34 K:1 D:2<br/>Muratpaşa / Antalya</b></div></div></section>
<footer><a className="brand brandImage" href="#"><img className="brandLogo" src="https://raw.githubusercontent.com/Teknoant/runtechh/main/runtechh-logo.png" alt="Runtechh Bilişim Teknolojileri" /></a><span>© 2026 Runtechh Bilişim Teknolojileri</span><a href="tel:+905326222235">0 532 622 22 35</a></footer>
</main>}