import type {Metadata} from "next";
import {notFound} from "next/navigation";
import MobileMenu from "../../components/MobileMenu";

const data={
"fiber-optik":["Fiber Optik Kablolama","Antalya fiber optik altyapı, füzyon sonlandırma, test ve devreye alma çözümleri.","Yüksek bant genişliği ve uzun mesafeli veri iletişimi için fiber optik altyapıyı keşiften devreye almaya kadar planlıyor ve uyguluyoruz.",["Fiber güzergâh ve kapasite planlama","Fiber kablo çekimi ve sonlandırma","Füzyon ek ve patch panel düzeni","Test, kontrol ve devreye alma"]],
"yapisal-kablolama":["Yapısal Kablolama","Antalya kurumsal data ve telefon yapısal kablolama çözümleri.","Ofis, otel, fabrika ve ticari yapılarda düzenli, etiketlenebilir ve büyütülebilir data ve telefon altyapıları kuruyoruz.",["Data ve telefon kablolama","Patch panel ve priz sonlandırma","Etiketleme ve kabinet düzeni","Test ve teslim"]],
"network":["Aktif Network ve Switch","Antalya kurumsal network, switch ve ağ altyapısı kurulumu.","Kapasite ve kullanıcı yoğunluğuna göre aktif ağ cihazlarını fiziksel altyapıyla birlikte planlıyor, kuruyor ve devreye alıyoruz.",["Ağ topolojisi planlama","Yönetilebilir switch kurulumu","VLAN ve ağ segmentasyonu altyapısı","Test ve devreye alma"]],
"wifi":["Kurumsal Wi-Fi","Antalya kurumsal Wi-Fi ve kablosuz ağ çözümleri.","Indoor ve outdoor alanlarda kapsama, kapasite ve kullanıcı yoğunluğuna göre yönetilebilir kablosuz ağ altyapısı oluşturuyoruz.",["Kapsama değerlendirmesi","Access point konumlandırma","Kurumsal kablosuz ağ kurulumu","Performans kontrolü"]],
"ip-kamera":["IP Kamera Sistemleri","Antalya IP kamera, kayıt ve uzaktan izleme sistemleri.","Kamera, kayıt ve network altyapısını birlikte değerlendirerek işletmeler için yönetilebilir IP güvenlik kamera sistemleri kuruyoruz.",["Kamera noktalarının planlanması","IP kamera ve kayıt altyapısı","Network entegrasyonu","Yetkili uzaktan erişim"]],
"rack-kabinet":["Rack Kabinet Çözümleri","Antalya rack kabinet kurulumu ve kabinet düzenleme çözümleri.","Network ve sistem ekipmanlarının güvenli, düzenli ve servis edilebilir biçimde konumlandırılması için rack kabinet altyapıları kuruyoruz.",["Kabinet seçimi ve yerleşim","Kablo yönetimi","Aktif cihaz yerleşimi","Düzenleme ve teslim"]],
"ups":["UPS Güç Kaynakları","Antalya kurumsal UPS güç kaynağı çözümleri.","Kritik bilişim altyapısının enerji kesintilerine karşı sürekliliğini destekleyen UPS sistemlerini ihtiyaca göre planlıyor ve devreye alıyoruz.",["Güç ihtiyacı değerlendirmesi","UPS kapasite planlama","Kurulum ve bağlantı","Kontrol ve devreye alma"]],
"elektrik":["UPS ve Şebeke Elektrik Altyapısı","Antalya bilişim sistemleri için UPS ve şebeke elektrik altyapısı.","Sistem odası ve aktif ağ ekipmanları için gerekli enerji dağıtımını bilişim altyapısıyla birlikte düzenli biçimde ele alıyoruz.",["Enerji ihtiyacı planlama","UPS ve şebeke dağıtımı","Priz ve bağlantı düzeni","Kontrol ve teslim"]],
"sistem-odasi":["Sistem Odası Kurulumu","Antalya sistem odası, rack kabinet ve network altyapısı düzenleme çözümleri.","Rack kabinet, enerji, network ve kablolama bileşenlerini servis edilebilir ve büyümeye uygun tek bir sistem odası mimarisinde topluyoruz.",["Rack kabinet yerleşimi","Patch panel ve kablo yönetimi","Network ve enerji düzeni","Etiketleme ve devreye alma"]]
} as const;
type Slug=keyof typeof data;
export function generateStaticParams(){return Object.keys(data).map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const x=data[slug as Slug];return x?{title:x[0],description:x[1],alternates:{canonical:"/hizmetler/"+slug}}:{}}
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const x=data[slug as Slug];if(!x)notFound();const wa="https://wa.me/905326222235?text=Merhaba%20Runtechh%2C%20%C3%BCcretsiz%20ke%C5%9Fif%20hakk%C4%B1nda%20bilgi%20almak%20istiyorum.";return <main><header className="nav"><a className="brand brandImage" href="/"><img className="brandLogo" src="https://raw.githubusercontent.com/Teknoant/runtechh/main/runtechh-logo.png" alt="Runtechh Bilişim Teknolojileri"/></a><nav><a href="/biz-kimiz">Biz Kimiz</a><a href="/hizmetler">Hizmetlerimiz</a><a href="/referanslar">Çalıştığımız Markalar</a><a href="/iletisim">İletişim</a></nav><a className="smallCta whatsappCta" href={wa} target="_blank" rel="noopener noreferrer">WhatsApp</a><MobileMenu/></header><section className="serviceDetailHero"><span className="eyebrow">RUNTECHH / ANTALYA</span><h1>{x[0]}</h1><p>{x[2]}</p><a className="primary whatsappPrimary" href={wa} target="_blank" rel="noopener noreferrer">WhatsApp'tan Keşif Talep Et</a></section><section className="serviceDetailBody"><div><span className="eyebrow">HİZMET KAPSAMI</span><h2>Planlı, düzenli ve yönetilebilir altyapı.</h2></div><div className="serviceDetailSteps">{x[3].map((v,i)=><article key={v}><b>{String(i+1).padStart(2,"0")}</b><h3>{v}</h3></article>)}</div></section><footer><a className="brand brandImage" href="/"><img className="brandLogo" src="https://raw.githubusercontent.com/Teknoant/runtechh/main/runtechh-logo.png" alt="Runtechh Bilişim Teknolojileri"/></a><span>© 2026 Runtechh Bilişim Teknolojileri</span></footer></main>}